export const BOT_COMMANDS = [
  { command: "start", description: "Open the Neyro trading terminal" },
  { command: "help", description: "Show all Neyro commands" },
  { command: "wallet", description: "Create or view your wallet" },
  { command: "deposit", description: "Show your deposit address" },
  { command: "balance", description: "NEAR balance" },
  { command: "portfolio", description: "Token holdings" },
  { command: "new", description: "Newest NEARly launches" },
  { command: "launch", description: "Launch a token on NEARly" },
  { command: "launch_status", description: "Check a pending NEARly launch" },
  { command: "launch_history", description: "View your previous NEARly launches" },
  { command: "launch_cancel", description: "Cancel an unfinished launch wizard" },
  { command: "withdraw", description: "Send NEAR or tokens out: /withdraw <amount|all> <token> <to>" },
  { command: "rhea_register", description: "Register a token for RHEA swaps" },
  { command: "rhea_recovery", description: "Check RHEA internal balances" },
  { command: "rhea_withdraw", description: "Recover an RHEA internal balance" },
  { command: "buy", description: "Buy a token with NEAR: /buy <token> <amount>" },
  { command: "sell", description: "Sell a token for NEAR: /sell <token> <amount|all>" },
  { command: "settings", description: "View and change trading settings" },
  { command: "health", description: "Bot and NEAR RPC status" }
] as const;
